version: 2

models:
  - name: mart_activities_by_sport
    description: "Aggregated activity metrics by sport type for dashboard visualizations"
    columns:
      - name: sport_type
        description: "Type of sport (Run, Ride, Walk, etc.)"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Total number of activities for this sport type"
      - name: total_distance_km
        description: "Total distance in kilometers"
      - name: total_moving_hours
        description: "Total moving time in hours"
      - name: avg_distance_km
        description: "Average distance per activity in kilometers"
      - name: avg_moving_minutes
        description: "Average moving time per activity in minutes"

  - name: mart_daily_activity_counts
    description: "Daily activity counts for calendar heatmap visualization"
    columns:
      - name: activity_date
        description: "Date of activities"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Number of activities on this date"
      - name: total_distance_km
        description: "Total distance on this date in kilometers"
      - name: total_moving_minutes
        description: "Total moving time on this date in minutes"
