version: 2

models:
  - name: rpt_activities_by_sport
    description: "Aggregated activity metrics by sport type for dashboard visualizations"
    columns:
      - name: sport_type
        description: "Type of sport (Run, Ride, Walk, etc.)"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Total number of activities for this sport type"
      - name: total_moving_hours
        description: "Total moving time in hours"
      - name: avg_moving_hours
        description: "Average moving time per activity in hours"

  - name: rpt_daily_activity_counts
    description: "Daily activity counts for calendar heatmap visualization"
    columns:
      - name: activity_date
        description: "Date of activities"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Number of activities on this date"

  - name: rpt_activity_summary
    description: "Overall activity summary statistics for dashboard KPIs"
    columns:
      - name: total_activities
        description: "Total number of activities"
      - name: total_active_days
        description: "Total number of unique days with activities"
      - name: total_hours
        description: "Total moving time in hours"
      - name: total_distance_miles
        description: "Total distance in miles"
      - name: total_elevation_gain_feet
        description: "Total elevation gain in feet"

  - name: rpt_distinct_years
    description: "Distinct years with activities for year filter dropdown"
    columns:
      - name: activity_year
        description: "Year of activity"
        tests:
          - unique
          - not_null
      - name: max_year
        description: "Maximum year across all activities"
