version: 2

models:
  - name: rpt_activities_by_sport
    description: "Aggregated activity metrics by sport type for dashboard visualizations"
    columns:
      - name: sport_type
        description: "Type of sport (Run, Ride, Walk, etc.)"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Total number of activities for this sport type"
      - name: total_moving_hours
        description: "Total moving time in hours"
      - name: avg_moving_hours
        description: "Average moving time per activity in hours"

  - name: rpt_daily_activity_counts
    description: "Daily activity counts for calendar heatmap visualization"
    columns:
      - name: activity_date
        description: "Date of activities"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Number of activities on this date"

  - name: rpt_activity_summary
    description: "Overall activity summary statistics for dashboard KPIs"
    columns:
      - name: total_activities
        description: "Total number of activities"
      - name: total_active_days
        description: "Total number of unique days with activities"
      - name: total_hours
        description: "Total moving time in hours"
      - name: total_distance_miles
        description: "Total distance in miles"
      - name: total_elevation_gain_feet
        description: "Total elevation gain in feet"

  - name: rpt_distinct_years
    description: "Distinct years with activities for year filter dropdown"
    columns:
      - name: activity_year
        description: "Year of activity"
        tests:
          - unique
          - not_null
      - name: max_year
        description: "Maximum year across all activities"

  - name: rpt_home_kpis
    description: "All-time aggregate KPIs for the home page"
    columns:
      - name: total_activity_count
        description: "Total number of activities"
      - name: total_distance
        description: "Total distance in miles"
      - name: total_moving_time
        description: "Total moving time in seconds"
      - name: total_elapsed_time
        description: "Total elapsed time in seconds"
      - name: total_elevation_gain
        description: "Total elevation gain in feet"
      - name: avg_distance
        description: "Average distance per activity in miles"
      - name: avg_speed
        description: "Average speed across all activities in mph"
      - name: avg_hr
        description: "Average heart rate across activities (optional)"
      - name: avg_power
        description: "Average power across activities (optional)"
      - name: last_activity_date
        description: "Date of the most recent activity"

  - name: rpt_home_daily_trends
    description: "Daily aggregated metrics for trend visualizations"
    columns:
      - name: activity_date
        description: "Date of activities"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Number of activities on this date"
      - name: total_distance
        description: "Total distance on this date in miles"
      - name: total_moving_time
        description: "Total moving time on this date in seconds"
      - name: total_elevation_gain
        description: "Total elevation gain on this date in feet"
      - name: avg_hr
        description: "Average heart rate for activities on this date"
      - name: avg_power
        description: "Average power for activities on this date"

  - name: rpt_sport_mix
    description: "Activity distribution by sport type"
    columns:
      - name: sport_type
        description: "Type of sport (Run, Ride, Walk, etc.)"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Total number of activities for this sport type"
      - name: total_distance
        description: "Total distance for this sport type in miles"
      - name: total_moving_time
        description: "Total moving time for this sport type in seconds"
      - name: total_elevation_gain
        description: "Total elevation gain for this sport type in feet"

  - name: rpt_year_kpis
    description: "Yearly aggregate KPIs for year page"
    columns:
      - name: year
        description: "Year of activities"
        tests:
          - unique
          - not_null
      - name: activity_count
        description: "Total number of activities in this year"
      - name: total_distance
        description: "Total distance in this year in miles"
      - name: total_moving_time
        description: "Total moving time in this year in seconds"
      - name: total_elevation_gain
        description: "Total elevation gain in this year in feet"
      - name: longest_distance
        description: "Longest single activity distance in miles"
      - name: hardest_elevation_gain
        description: "Highest single activity elevation gain in feet"
      - name: avg_distance
        description: "Average distance per activity in miles"
      - name: avg_speed
        description: "Average speed in mph"
      - name: avg_hr
        description: "Average heart rate (optional)"
      - name: avg_power
        description: "Average power (optional)"
      - name: avg_weekly_distance
        description: "Average distance per week in miles"

  - name: rpt_year_monthly
    description: "Monthly aggregates for year page charts"
    columns:
      - name: month_start_date
        description: "First day of the month"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year"
      - name: month
        description: "Month number (1-12)"
      - name: month_name
        description: "Month name (Jan-Dec)"
      - name: activity_count
        description: "Number of activities in this month"
      - name: total_distance
        description: "Total distance in this month in miles"
      - name: total_moving_time
        description: "Total moving time in this month in seconds"
      - name: total_elevation_gain
        description: "Total elevation gain in this month in feet"

  - name: rpt_activity_list
    description: "Activity listing for navigation and tables"
    columns:
      - name: activity_id
        description: "Unique activity identifier"
        tests:
          - unique
          - not_null
      - name: activity_name
        description: "Name of the activity"
      - name: started_at
        description: "UTC start time of the activity"
      - name: started_at_local
        description: "Local start time of the activity"
      - name: sport_type
        description: "Type of sport"
      - name: distance
        description: "Distance in miles"
      - name: moving_seconds
        description: "Moving time in seconds"
      - name: elevation_gain
        description: "Elevation gain in feet"
      - name: hr_avg
        description: "Average heart rate (optional)"
      - name: power_avg
        description: "Average power (optional)"

  - name: rpt_activity_detail
    description: "Complete activity details for activity detail page"
    columns:
      - name: activity_id
        description: "Unique activity identifier"
        tests:
          - unique
          - not_null
      - name: activity_name
        description: "Name of the activity"
      - name: activity_type
        description: "General activity type"
      - name: sport_type
        description: "Specific sport type"
      - name: workout_type
        description: "Workout classification (Race, Long Run, Workout, None)"
      - name: started_at
        description: "UTC start time"
      - name: started_at_local
        description: "Local start time"
      - name: timezone
        description: "Timezone of the activity"
      - name: elapsed_seconds
        description: "Total elapsed time in seconds"
      - name: moving_seconds
        description: "Moving time in seconds"
      - name: distance
        description: "Distance in miles"
      - name: distance_metric
        description: "Distance in kilometers"
      - name: elevation_gain
        description: "Elevation gain in feet"
      - name: elevation_min
        description: "Minimum elevation in feet"
      - name: elevation_max
        description: "Maximum elevation in feet"
      - name: speed_avg
        description: "Average speed in mph"
      - name: speed_max
        description: "Maximum speed in mph"
      - name: speed_avg_metric
        description: "Average speed in kph"
      - name: speed_max_metric
        description: "Maximum speed in kph"
      - name: has_heartrate
        description: "Whether HR data is available"
      - name: hr_avg
        description: "Average heart rate"
      - name: hr_max
        description: "Maximum heart rate"
      - name: power_avg
        description: "Average power in watts"
      - name: kilojoules
        description: "Energy output in kilojoules"
      - name: calories_burned
        description: "Estimated calories burned"
      - name: is_device_watts
        description: "Whether power is from device (vs estimated)"
      - name: kudos_count
        description: "Number of kudos received"
      - name: comment_count
        description: "Number of comments"
      - name: achievement_count
        description: "Number of achievements earned"
      - name: pr_count
        description: "Number of personal records"
      - name: suffer_score
        description: "Strava suffer score"
      - name: is_commute
        description: "Whether this is a commute"
      - name: is_trainer
        description: "Whether this is a trainer activity"
      - name: is_manual
        description: "Whether this was manually entered"
      - name: is_private
        description: "Whether this activity is private"
      - name: map_id
        description: "Map identifier"
      - name: gear_id
        description: "Gear identifier"

  - name: rpt_activity_hr_zones
    description: "Heart rate zone distribution per activity"
    columns:
      - name: activity_id
        description: "Activity identifier"
        tests:
          - not_null
      - name: zone_id
        description: "Zone number (1-5)"
        tests:
          - not_null
      - name: zone_name
        description: "Zone name (Z1-Z5)"
      - name: seconds_in_zone
        description: "Time spent in this zone in seconds"
      - name: zone_min_bpm
        description: "Minimum heart rate for this zone"
      - name: zone_max_bpm
        description: "Maximum heart rate for this zone"
      - name: pct_in_zone
        description: "Percentage of total time in this zone"
      - name: is_sensor_based
        description: "Whether data is from sensor"
      - name: has_custom_zone_set
        description: "Whether custom zones are defined"

  - name: rpt_activity_power_zones
    description: "Power zone distribution per activity"
    columns:
      - name: activity_id
        description: "Activity identifier"
        tests:
          - not_null
      - name: zone_id
        description: "Zone number (1-5)"
        tests:
          - not_null
      - name: zone_name
        description: "Zone name (Z1-Z5)"
      - name: seconds_in_zone
        description: "Time spent in this zone in seconds"
      - name: zone_min_watts
        description: "Minimum power for this zone"
      - name: zone_max_watts
        description: "Maximum power for this zone"
      - name: pct_in_zone
        description: "Percentage of total time in this zone"
      - name: is_sensor_based
        description: "Whether data is from sensor"
      - name: has_custom_zone_set
        description: "Whether custom zones are defined"
