name: 'strava_transform'
version: '1.0.0'

profile: 'strava_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

flags:
  send_anonymous_usage_stats: false
  use_colors: true

vars:
  # Default timezone for local time conversions
  local_timezone: 'America/New_York'

models:
  strava_transform:
    +tags: ["strava"]

    staging:
      +materialized: view
      +tags: ["staging"]
      +schema: staging

    intermediate:
      +materialized: view
      +tags: ["intermediate"]
      +schema: intermediate
      # Override for incremental models
      int_strava__activity_stream_points:
        +materialized: incremental

    marts:
      +materialized: table
      +tags: ["marts"]
      +schema: marts

    reporting:
      +materialized: table
      +tags: ["reporting"]
      +database: reporting
      +schema: reporting
